// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPeaQiGvj4Vv4SLIFYjIEKTluf4Nvi8k',
    appId: '1:1093905579400:web:YOUR_WEB_APP_ID',
    messagingSenderId: '1093905579400',
    projectId: 'mylearning-83b49',
    authDomain: 'mylearning-83b49.firebaseapp.com',
    storageBucket: 'mylearning-83b49.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPeaQiGvj4Vv4SLIFYjIEKTluf4Nvi8k',
    appId: '1:1093905579400:android:95cd0117b3316a05f24e3d',
    messagingSenderId: '1093905579400',
    projectId: 'mylearning-83b49',
    storageBucket: 'mylearning-83b49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPeaQiGvj4Vv4SLIFYjIEKTluf4Nvi8k',
    appId: '1:1093905579400:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '1093905579400',
    projectId: 'mylearning-83b49',
    storageBucket: 'mylearning-83b49.firebasestorage.app',
    iosBundleId: 'com.mlq.myLeadershipQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrPeaQiGvj4Vv4SLIFYjIEKTluf4Nvi8k',
    appId: '1:1093905579400:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '1093905579400',
    projectId: 'mylearning-83b49',
    storageBucket: 'mylearning-83b49.firebasestorage.app',
    iosBundleId: 'com.mlq.myLeadershipQuest',
  );
}
